@startuml

title __DEMO's Class Diagram__\n

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Benchmark {
        + elementCount : int
        ~ cars : Car[]
        ~ ids : String[]
        + generateElements()
        {static} + main()
        + putMap()
        {static} + putMappings()
        + removeCarMap()
        {static} ~ generateElements()
        {static} ~ generateIds()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Benchmark.FullMap {
        ~ cars : Car[]
        ~ carsMap : HashMap<String, Car>
        ~ ids : String[]
        + fillCarMap()
        + generateElementsAndIds()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Car {
        {static} - currentYear : int
        - make : String
        {static} - maxPrice : double
        - mileage : int
        {static} - minPrice : double
        {static} - minYear : int
        - model : String
        - price : double
        - year : int
        + Car()
        + Car()
        + Car()
        + Car()
        + equals()
        + getMake()
        + getMileage()
        + getModel()
        + getPrice()
        + getYear()
        + hashCode()
        + parse()
        + setMileage()
        + setPrice()
        + toString()
        - validate()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.Car.Builder {
        {static} - MODELS : String[][]
        {static} - RANDOM : Random
        - make : String
        - mileage : int
        - model : String
        - price : double
        - year : int
        + build()
        + buildRandom()
        + make()
        + mileage()
        + model()
        + price()
        + year()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.CarsGenerator {
        {static} - ID_CODE : String
        - cars : Car[]
        - currentCarIdIndex : int
        - currentCarIndex : int
        - keys : String[]
        {static} - serNr : int
        {static} + generateShuffleCars()
        + generateShuffleCarsAndIds()
        {static} + generateShuffleIds()
        + getCar()
        + getCarId()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.DemoExecution {
        {static} + main()
        + start()
    }
  }
  

  namespace edu.ktu.ds.lab3.demo {
    class edu.ktu.ds.lab3.demo.ManualTest {
        {static} + executeTest()
        {static} + main()
    }
  }
  

  edu.ktu.ds.lab3.demo.Benchmark +-down- edu.ktu.ds.lab3.demo.Benchmark.FullMap
  edu.ktu.ds.lab3.demo.Car .up.|> edu.ktu.ds.lab3.utils.Parsable
  edu.ktu.ds.lab3.demo.Car +-down- edu.ktu.ds.lab3.demo.Car.Builder
  edu.ktu.ds.lab3.demo.DemoExecution -up-|> javafx.application.Application


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
